Designed UI
VICTOR-CHUKWU/react-calculator pull request #2
Opened 2021-10-26 21:33 UTC by VICTOR-CHUKWU

Created component folder
created calculator js
designed UI

2021-10-26 21:49 UTC, Elbie-em reviewed
## STATUS:  INVALID CRR 🔴 ❌

Hi @VICTOR-CHUKWU, while you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project that does not use [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md). 
Kindly create a development branch and this should be the base of comparison for this PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Kindly submit another review request once done and please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

> Elbie Moonga (Part-time  Code Reviewer)

2021-10-27 07:00 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-10-27 07:00 UTC, arslanbisharat commented on src/App.js
> +      <Calculator />
- [ ] APP should be class-based. Please have a look at the project requirements.

2021-10-27 07:00 UTC, arslanbisharat commented on src/component/Calculator.js
> +/* eslint-disable react/prefer-stateless-function */
- [ ] Let's not disable eslint rules. These are here to write clean code.

2021-10-27 07:51 UTC, dasileker approved these changes
## **Hi @VICTOR-CHUKWU,**


## **Congratulations! 🎉 Project Approved**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-27 08:54 UTC, merged